registry: 'https://registry.npm.taobao.org'
disturl: 'https://npm.taobao.org/dist'
electron_mirror: 'https://npm.taobao.org/mirrors/electron/'
node_inspector_cdnurl: 'https://npm.taobao.org/mirrors/node-inspector'
fsevents_binary_host_mirror: 'http://npm.taobao.org/mirrors/fsevents/'
msvs_version: '2017'
