strategy:
  matrix:
    mac:
      imageName: 'macOS-latest'
      buildPlatform: 'mac'
    windows:
      # https://github.com/nodegit/nodegit/issues/1842
      imageName: 'vs2017-win2016'
      buildPlatform: 'win'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: $(imageName)

trigger:
  batch: true
  branches:
    include:
      - master
# pr:
#   - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - task: Cache@2
    displayName: Cache Yarn packages
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  - script: yarn --frozen-lockfile
    displayName: yarn install
    env:
      DISPLAY: ':99.0'
      REGISTRY: 'https://registry.npmjs.org'
  - script: yarn package --$(buildPlatform)
    displayName: yarn package
  - script: yarn run publish:qiniu
    displayName: yarn publish
    workingDirectory: ./src
