variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - script: |
      npm i -g yarn
      yarn config set registry https://registry.npm.taobao.org
    displayName: Install yarn
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - script: yarn --frozen-lockfile
    env:
      DISPLAY: ':99.0'
    displayName: yarn
  - script: yarn package --win
    displayName: yarn package
  - script: yarn run publish:qiniu
    workingDirectory: ./src
    displayName: yarn publish:qiniu
