variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: macOS-10.15

trigger:
  batch: true
  branches:
    include:
      - master-runtime
# pr:
#   - master-runtime

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - task: Cache@2
    displayName: Cache Yarn packages
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
  - script: yarn --frozen-lockfile
    displayName: yarn install
    env:
      DISPLAY: ':99.0'
      REGISTRY: 'https://registry.npmjs.org'
  - script: yarn package:with_runtime --mac
    displayName: yarn package
    env:
      REGISTRY: 'https://registry.npmjs.org'
      CSC_LINK: 'https://cdn.socode.pro/derealize.p12'
      CSC_KEY_PASSWORD: 'z565656z#'
  - script: yarn run publish:qiniu
    displayName: yarn publish
    workingDirectory: ./src
