variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: macOS-latest

trigger:
  batch: true
  branches:
    include:
      - master-runtime
# pr:
#   - master-runtime

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - task: Cache@2
    displayName: Cache Yarn packages
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
  - script: yarn --frozen-lockfile
    displayName: yarn install
    env:
      DISPLAY: ':99.0'
  - script: yarn package:with_runtime --mac
    displayName: yarn package
  - script: yarn run publish:qiniu
    displayName: yarn publish
    workingDirectory: ./src
